### ISSUE TITLE
Weird Behavior on quotation marks

### ISSUE THREAD

**Issue by LucasMW** [danielcardeenas/AudioStego#12]
This works:
`$./hideme ~/Music/Machine_Takeover.mp3 "'There is a message'"`

> Doing it boss! 
> Spreading level: 297022
> Header wrote
> File has been saved as: output.mp3
> Hiding process has finished successfully.
> Cleaning memory...

`$ ./hideme output.mp3 -f`

> Doing it boss! 
> Looking for the hidden message...
> String detected. Retrieving it...
> Message recovered size: 20 bytes
> Message: 'There is a message'
> Recovering process has finished successfully.
> Cleaning memory...

But, somehow, this doesn't:

`./hideme ~/Music/Machine_Takeover.mp3 "There is a message"`

> libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
> Abort trap: 6

Why the **"'** are necessary? 
The message comes with it 
> Message: 'There is a message'

I get the instructions tell to use **"'**. 
But this behavior is weird
And this seems to be a bug.

**Comment by LucasMW** [comment]
The results were found on  Mac OS 10.13.6 (High Sierra) 
Asset "Machine_Takeover.mp3" can be found here http://teknoaxe.com/Link_Code_3.php?q=1385

**Comment by danielcardeenas** [comment]
It's not a bug, this is how the application detects if its a file path or a string
