### ISSUE TITLE
hidden mp3

### ISSUE THREAD

**Issue by Banginpadr** [danielcardeenas/AudioStego#2]
im new to this so i have a question that must be a dumb one tho. my question is that if i hade something into a .mp3 file, i just can send it to one of my friends and he will be available to decoded without having to install this git?or he need to have this in his pc to read what ever i hade into it? and what about the size of the file im trying to hide, can i hide 1gb into a mp3 song too? 
thank you

**Comment by danielcardeenas** [comment]
Hi.
To recover the message you will need this program too.
Also of course you cannot hide **1GB** into a **4MB** .mp3 song hahahaha.
If I remember correctly, the program will tell you if the file or text you want to hide is suitable for hiding.

Keep in mind the bigger the file you want to hide the higher probablility to the sound to be distorted.

**Comment by Banginpadr** [comment]
@danielcardeenas thank you for your response. yeah, you was right about that size. it works best with hiding fotos. i tested it saving a folder with 2 .txt on it but when i ran ./HideMeIn -f the out put was a blak file not the folder

**Comment by danielcardeenas** [comment]
It is not possible to hide a folder. You will have to compress the folder as a file like .zip or .rar

**Comment by Banginpadr** [comment]
@danielcardeenas thank you
