### ISSUE TITLE
Able to hear clicks in encoded file

### ISSUE THREAD

**Issue by songproducer** [danielcardeenas/AudioStego#3]
Is there any way to make the encoded message sound less bad?

**Comment by danielcardeenas** [comment]
Use `.wav` or `.flac` or whatever type of file that is usually bigger than `.mp3`

**Comment by songproducer** [comment]
Thanks, I already tried with .wav and it still has clicks, though the compression is less noticeable. Do you know if I can change the code to make the clicks into other sounds?

**Comment by danielcardeenas** [comment]
Of course you can. This is a really simple method I used when I was young. A better approach would be using [LSB](https://en.wikipedia.org/wiki/Least_significant_bit

**Comment by songproducer** [comment]
Thanks, will study up on LSB.
